### ISSUE TITLE
Documentation for busid differs from expected configuration file

### ISSUE THREAD

**Issue by mattyvau** [AverageJoe89/hassio-usbip-mounter#3]
The addon expects the USB device busid to be referred to as "bus_id" in the config file. The documentation currently states the configuration file for the addon takes the form of:
```
devices:
  - server_address: 10.0.0.100 
    bind: 1-1.4
```
This results in the following error when  trying to save the config. 
> Failed to save add-on configuration, Missing option 'bus_id' in devices in USBIP Mounter (50dbf9c6_usbip). Got {'devices': [{'server_address': '10.0.0.100', 'bind': '1-1.4'}]}

This is fixed by changing the file to:

```
devices:
  - server_address: 10.0.0.100 
    bus_id: 1-1.4
```

**Comment by AverageJoe89** [comment]
Fixed at 6efe259a89a5125671e95c4beb34f6707d166cbf
