### ISSUE TITLE
WARNING: usbipd crashed, halting add-on

### ISSUE THREAD

**Issue by xxLexanixx** [AverageJoe89/hassio-usbip-mounter#6]
Hello,

I installed the addon today because I use USBIPD on my server.
I entered the IP address from the server and the ID from the USB stick in the configuration, unfortunately the addon keeps crashing with the error

usbipd: info: starting usbipd (usbip-utils 2.0)
usbipd: error: bind: 0.0.0.0:3240: 98 (Address in use)
usbipd: error: bind: :::3240: 98 (Address in use)
usbipd: error: failed to open a listening socket
[14:38:48] WARNING: usbipd crashed, halting add-on
++ mount -o remount -t sysfs sysfs /sys
[14:38:48] INFO: usbipd stopped, restarting...
++ /usr/sbin/usbip --debug attach -r 192.168.xxx.xx -b 3-4
usbip: debug: usbip.c:129:[run_command] running command: `attach'
usbip: debug: usbip_network.c:199:[usbip_net_recv_op_common] request failed at peer: 2
usbip: error: Attach Request for 3-4 failed - Device busy (exported)

However, it still seems to work, but as soon as the stick has been loaded the addon goes into error and restarts again and again.

**Comment by AverageJoe89** [comment]
It looks like something is already occupied port 3240 and daemon cannot start.
`usbipd: error: bind: 0.0.0.0:3240: 98 (Address in use)`

Try to restart HA so you have clean setup, or use `netstat -lap` to see what is running there
