### ISSUE TITLE
Dns server name

### ISSUE THREAD

**Issue by jflefebvre06** [AverageJoe89/hassio-usbip-mounter#8]
Please allow dns server name, not only IP

**Comment by KaninchenSpeed** [comment]
I made a fork for this some time ago: [KaninchenSpeed/hassio-usbip-mounter](https://github.com/KaninchenSpeed/hassio-usbip-mounter)

**Comment by AverageJoe89** [comment]
Should be fixed by https://github.com/AverageJoe89/hassio-usbip-mounter/pull/11
