### ISSUE TITLE
How to pass through Warema Stick to RPI4 running HAOS?

### ISSUE THREAD

**Issue by Aaroneisele55** [AverageJoe89/hassio-usbip-mounter#9]
Hello,
I have a Warema Stick to control my blind motors, but the blinds are located too far away from my HA Host for the stick to reach them, so I would like to use USBip.
What path does the Add-on mount the stick to?
I didn't find it when I looked for it....
The Warema Stick is recognised as an FTDI USB to serial adapter, if that helps....

Best regards
Aaron Eisele

**Comment by AverageJoe89** [comment]
Not sure what you're trying to achieve, but you need host with running usbip, this may help https://developer.ridgerun.com/wiki/index.php/How_to_setup_and_use_USB/IP

**Comment by Aaroneisele55** [comment]
> Not sure what you're trying to achieve, but you need host with running usbip, this may help https://developer.ridgerun.com/wiki/index.php/How_to_setup_and_use_USB/IP

Sorry,
I already implemented USBip a few months ago and forgot to close this...
